
FROM ubuntu:20.04                                      # Use the official Ubuntu as a parent image

RUN apt-get update && apt-get install -y nginx         # Update the package list and install Nginx

RUN rm -f /var/www/html/index.nginx-debian.html        # Remove the default Nginx index.html file
 
COPY ./index.html /var/www/html/                       # Copy custom static files or configuration (optional)

EXPOSE 80                                              # Expose port 80 to allow web traffic

CMD ["nginx", "-g", "daemon off;"]                      # Start Nginx in the foreground


##### Create a multi-stage Dockerfile.

FROM maven:3.9-amazoncorretto-17 AS build

WORKDIR /app

COPY . .

RUN mvn clean package

FROM amazoncorretto:17

COPY --from=build /app/target/*.jar app.jar

CMD ["java","-jar","app.jar"]
